---- TRY AND CATCH ----
BEGIN TRY
BEGIN TRANSACTION
	DECLARE @ERRORRESULTS VARCHAR(50)
	BEGIN TRANSACTION
	INSERT INTO Persons (PersonID, FirstName, LastName, Address, City, Marks) VALUES (1, 'Siddharth', 'Chatterjee', 'Kandivali West', 'Mumbai', 8)
	COMMIT TRANSACTION
END TRY

BEGIN CATCH
	PRINT 'CATCH STATEMENT ENTERED'
	ROLLBACK TRANSACTION
END CATCH