---- CUSTOM ERROR MESSAGES ----

SELECT * FROM Persons

BEGIN TRANSACTION
	UPDATE Persons
	SET PersonID = 20
	WHERE PersonID = 5
COMMIT TRANSACTION

DECLARE @ERRORRESULTS VARCHAR(50)
BEGIN TRANSACTION
INSERT INTO Persons (PersonID, FirstName, LastName, Address, City, Marks) VALUES (1, 'Siddharth', 'Chatterjee', 'Kandivali West', 'Mumbai', 8);

SET @ERRORRESULTS = @@ERROR

IF (@ERRORRESULTS = 0)
BEGIN
	PRINT 'SUCCESS!!'
	COMMIT TRANSACTION
END
ELSE
BEGIN
	RAISERROR('STATEMENT FAILED - THIS IS MY CUSTOM MESSAGE',16,1)
	ROLLBACK TRANSACTION
END