---- TRANSACTIONS ----
SELECT * FROM Persons

BEGIN TRANSACTION
	UPDATE Persons
	SET PersonID = 20
	WHERE PersonID = 5
COMMIT TRANSACTION

DECLARE @ERRORRESULTS VARCHAR(50)
BEGIN TRANSACTION
INSERT INTO Persons (PersonID, FirstName, LastName, Address, City, Marks) VALUES (11, 'Rishank', 'Pandey', 'Malad East', 'Mumbai', 8);

SET @ERRORRESULTS = @@ERROR

IF (@ERRORRESULTS = 0)
BEGIN
	PRINT 'SUCCESS!!'
	COMMIT TRANSACTION
END
ELSE
BEGIN
	PRINT 'STATEMENT FAILED!'
	ROLLBACK TRANSACTION
END
