----DATABASE LEVEL TRIGGER----
CREATE TRIGGER Demo_DBLevelTrigger
ON DATABASE
AFTER CREATE_TABLE
AS
BEGIN
PRINT 'CREATION OF NEW TABLES NOT ALLOWED'
ROLLBACK TRANSACTION
END 
GO

--TEST THE TRIGGER--
CREATE TABLE Employees(Col1 varchar(10))