---- FUNCTIONS RETURNING TABLES ----

CREATE FUNCTION PERSON_TABVALUED
(@PersonID INT)
RETURNS TABLE
AS RETURN
SELECT FirstName, LastName, Address
FROM Persons
WHERE PersonID = @PersonID

SELECT FirstName, LastName FROM dbo.PERSON_TABVALUED(10)
