----USER DEFINED FUNCTIONS----
USE Jan23TrainingDB9

CREATE FUNCTION PERSONMARKS()
RETURNS INT
AS
BEGIN
DECLARE @PERSONMARKS AS INT
SELECT @PERSONMARKS = SUM(MARKS) FROM Persons
RETURN @PERSONMARKS
END

DECLARE @PERSONRESULTS INT
SELECT @PERSONRESULTS = dbo.PERSONMARKS()
PRINT @PERSONRESULTS
