----PARAMETRIZED FUNCTION----

CREATE FUNCTION PERSONS_GROUP
(@GROUP VARCHAR(50))

RETURNS INT
AS
BEGIN
DECLARE @PERSONMARKS AS INT
SELECT @PERSONMARKS = SUM(MARKS) FROM Persons
WHERE [Marks] = @GROUP
RETURN @PERSONMARKS
END

DECLARE @PERSONRESULTS INT
SELECT @PERSONRESULTS = dbo.PERSONS_GROUP(7)
PRINT @PERSONRESULTS
